[package]

name = "ferrum"
version = "0.0.2"
authors = [ "Nikita Pekin <contact@nikitapek.in>" ]

[[bin]]

name = "ferrum"
path = "src/main.rs"

[dependencies]
getopts = "0.2.4"
log = "0.2.5"
peg = "0.1.8"

[dependencies.rust-mustache]
git = "https://github.com/nickel-org/rust-mustache"
