[package]

name = "ferrum"
version = "0.0.1"
authors = []

[[bin]]

name = "ferrum"
path = "src/main.rs"

[dependencies]
getopts = "*"
log = "*"
peg = "*"

[dependencies.rust-mustache]
git = "https://github.com/nickel-org/rust-mustache"
