[package]

name = "ferrum"
version = "0.0.1"
authors = []

[[bin]]

name = "ferrum"
path = "src/main.rs"

[dependencies.nickel]

git = "https://github.com/nickel-org/nickel"

[dependencies.peg]

git = "https://github.com/kevinmehall/rust-peg"

[dependencies.toml]

git = "https://github.com/alexcrichton/toml-rs"
